= Meaningful Names
:google_cpp_style_guide_url: https://google.github.io/styleguide/cppguide.html
:abc_url: https://bitbucket.org/alanmi/abc
:promise_naming_url: http://stackoverflow.com/questions/14267346/javascript-naming-convention-for-promises

== Use Intention-Revealing Names

The name of a variable, function, or class should tell you

* why it exists.
* what is does.
* how it is used.

For example, comparing this one:

[source, cpp]
----
int enemies = 10; // Record the number of remaining enemies.
----

with this one:

[source, cpp]
----
int num_remaining_enemies = 10;
----

Obviously, the second one, which is expressive without a comment, is much
better.

== Avoid Disinformation

* Does it imply its type? +
  `pointVector` => `std::vector<Point>` ?
* How to quickly spot their difference? +
  `NTUPlacerForEfficientPlacingOfMacros` +
  `NTUPlacerForEfficientRoutingOfMacros`
* WTF? +
  `if (O == l)` +
  `if (O == 1)` +
  `if (0 == l)` +
  `if (0 == 1)`

== Make Meaningful Distinctions

* Do not use number-series +
  `a1, a2, ..., aN`
* Do not add noise words +
  `Product` +
  `ProductInfo` +
  `ProductData`

== Use Pronounceable Names

Good for communications.

For example, +
"`Hey, Nady, What's the purpose of class `CustmrRcrd`?`" vs +
"`Hey, Nady, What's the purpose of class `CustomerRecord`?`"

== Use Searchable Names

Do not use single-letter name and numerics constants.

____
Personally, I use single-letter names only in the following situations:

* Loop control variables

[source, cpp]
----
for (int i = 0; i < 10; ++i)
----

* Math symbols

[source, python]
----
from sympy import Symbol, limit, oo
n = Symbol("n")
e = limit((1 + 1 / n) ** n, n, oo) # Euler's number
----
____

== Avoid Encodings

Do not encoding type or scope information into names.

For example,

* no Hungarian notation.
* no member prefix (or suffix), such as `m_` or `_m`.

____
However, I prefer to append an underscore to a member variable.
footnote:[Usually, I follow link:{google_cpp_style_guide_url}#Variable_Names[Google
C++ style guide].]

[source, cpp]
----
class Person {
  std::string name_;
  int age_;
};
----
____

== Avoid Mental Mapping

Do not show off your smart.

For example, use `pswd_8aAd` to represent a password which must have at least

* 8 lower-case alphabet
* 1 upper-case alphabet
* 1 digit

Can you see the logic behind this name instantly?

Be professional: *Clarity* is king.

== Class Names

Do use a *noun*.

Avoid words like `Manager`, `Processor`, `Data` and `Info`.

____
Nevertheless, I have seen some code containing classes with `Manager` in their
names, and it still works great. For example, link:{abc_url}[ABC], a program
that I recently used, has some type names ended with `Man`, and not only is it
well-maintained, but also improved constantly. Therefore, I don't think that
using `Manager` in names should be prohibited completely, yet it should not be
abused. I think the proper scenario to use it would be a container-like class.
For example, if you need a class to manage resources like `Circuit` objects, and
there is no logically right name for the class, picking `CircuitsManager` would
be acceptable. It's a last resort IMO though.
____

== Method Names

Do start with a *verb*.

____
I prefer to name accessors and mutators in the following way:

[source, cpp]
----
Vertex source;
source.SetName("src");
source.Name(); // "src"
source.IsVisited(); // false
----
____

== Don't Be Cute

Do not try to be humorous.

For example, choose `DeleteTable()` over `Boom()`.

== Pick One Word per Concept

Do choose *only* one word for a concept.

For example,

* `retrieve`, `fetch` or `get`
* `display`, `show` or `print`
* `eliminate`, `remove` or `delete`

____
Recently, I start learning `Promise` in JavaScript, having a hard time coming up
a rational naming rule for functions that return `Promise`. The reason why it is
so difficult to name these functions is that we usually want to _get_ a result
from calling them. However, instead of getting the result we want immediately,
we get a `Promise`, an object that will give you the result only at some point.
So what the function return is essentially a result that is still _loading_.

Here is a solution that may be somehow desirable.footnote:[It's the best
link:{promise_naming_url}[suggestion] AFAIK.]

[source, javascript]
----
const imageLoading = loadImage(url);
imageLoading
  .then(onFulfillment)
  .catch(onRejection);
----
____

== Don't Pun
